# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MainInclinometrDialog
                                 A QGIS plugin
 Расчет нклинометрии
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2026 by GPN-GEO
        email                : jjj@kkk.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os 
import json
import random

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import Qt

from qgis.core import (
    QgsMapLayerProxyModel,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY,
    QgsVectorLayer,
    QgsField,
    QgsFields,
    QgsFeature
)

# Для функции выбора устья
from qgis.gui import QgsMapToolIdentifyFeature
from qgis.utils import iface

from PyQt5.QtCore import QVariant

from .mathematics import Mathematics
from .excel_reader import ExcelReader
from .layer_manager import LayerManager

# ==========================================================
# Загрузка интерфейса Qt Designer
# ==========================================================

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        "inclinometr_dialog_base.ui"
    ),
    from_imports=True,
    import_from="inclinometr"
)



# ==========================================================
# Главный класс плагина
# ==========================================================

class MainInclinometrDialog(QtWidgets.QDialog, FORM_CLASS):

    # ======================================================
    # Инициализация
    # ======================================================

    def __init__(self, parent=None):
        """Constructor."""

        super(MainInclinometrDialog, self).__init__(parent)
        self.math = Mathematics(self)
        self.setupUi(self)
        self.setFixedSize(self.size())        
        
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        self.show()

        self.layerManager = LayerManager(self)

        # %% Вкладка --- Устье ---

        
        # Инструмент выбора
        self.wellHeadIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.targetIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.selectedWellHead = None
        # Система координат слоя
        self.crsLayerWellHead = None
        # Выбранная система координат
        self.crsOutputWellHead = None
        
        # Фильтр списка слоев - только слои точек
        # self.mMapLayerComboBoxWellHead.setFilters(
        #     QgsMapLayerProxyModel.PointLayer
        # )
        # Обработка события выбора слоя устьев
        # self.mMapLayerComboBoxWellHead.layerChanged.connect(
        #     self.mMapLayerComboBoxWellHeadChanged
        # )

        

        # Подключаем кнопку
        self.btnSelectWellHead.clicked.connect(
            self.selectWellHead
        )

        self.mQgsProjectionSelectionWidgetWellHead.crsChanged.connect(
            self.wellHeadCrsChanged
        )
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )

        # %% Вкладка --- Цели ---

        
        self.selectedTarget = None

        # Код месторождения выбранного устья
        self.fieldCode = ""
          
        # При выборе цели из списка
        self.cmbTarget.currentIndexChanged.connect(
            self.targetChanged
        )
        

        # %% Вкладка --- Слои

        # исходные слои которые БУДУТ включены в рабочие слои
        self.positionLayers = []
        self.targetLayers = []
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxPositions.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxTargets.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        
        # Подключение кнопок для выбора слоев
 
        self.btnAddPositionLayer.clicked.connect(self.layerManager.addPositionLayer)
        self.btnRemovePositionLayer.clicked.connect(self.layerManager.removePositionLayer)

        self.btnAddTargetLayer.clicked.connect(self.layerManager.addTargetLayer)
        self.btnRemoveTargetLayer.clicked.connect(self.layerManager.removeTargetLayer)

        # добавление кнопок создания рабочих слоев
        self.btnCreatePositionsLayer.clicked.connect(self.layerManager.createPositionsLayer)
        self.btnCreateTargetsLayer.clicked.connect(self.layerManager.createTargetsLayer)
        
        # Рабочие слои
        self.layerPositions = None
        self.layerTargets = None
        self.layerOilfields = None
        
        self.btnCreateOilFieldsLayer.clicked.connect(self.layerManager.createOilFieldsLayer)
        
        self.btnSelectTarget.clicked.connect(
            self.selectTarget
        )
        
        # Система координат слоя целей
        self.crsLayerTarget = None
        
        # Система координат вывода целей
        self.crsOutputTarget = None
        
        
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )
        
        
        self.selectedTargets = []
        
        self.excel = ExcelReader(self)
 

        self.btnLoadInclinometry.clicked.connect(
            self.math.loadInclinometry
        )


        self.btnCalculateInclinometry.clicked.connect(
            self.math.calculateInclinometry
        )
        self.btnCalculateDeviation.clicked.connect(
            self.math.calculationDeviation
        )

    # ======================================================
    # Вкладка "Устье"
    # ======================================================


    def selectWellHead(self):
        self.selectFeature(
            self.wellHeadSelected
        )


    def selectFeature(self, callback):
        """Универсальная функция выбора объекта на карте"""
        layers = QgsProject.instance().mapLayersByName("Positions_WORK")
        layer = layers[0] if layers else None
        self.crsLayerWellHead = layer.crs()
        self.crsOutputWellHead = layer.crs()
        self.layerWellHead = layer

        if layer is None:
            QMessageBox.warning(
                self,
                "Внимание",
                "Сначала выберите слой."
            )
            return

        self.wellHeadIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
        self.wellHeadIdentifyTool.setLayer(layer)
        self.wellHeadIdentifyTool.featureIdentified.connect(
            callback
        )

        iface.mapCanvas().setMapTool(
            self.wellHeadIdentifyTool
        )


    def wellHeadSelected(self, feature):
        # Сохраняем выбранный объект
        self.selectedWellHead = feature
        
        plugin_dir = os.path.dirname(__file__)
        settings_path = os.path.join(
            plugin_dir,
            "settings",
            "settings.json"
        )
        
        with open(settings_path, encoding="utf-8") as f:
            settings = json.load(f)
            
    
            # QMessageBox.information(self, "Слой", "Это устья ГеоБД")
            self.txtWellHeadName.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["name"]])
            )
            self.txtWellHeadGround.setText("")
            self.txtWellHeadRotor.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["rotor"]])
            )
            self.txtWellHeadLicense.setText(
                str(feature[settings["WellHead"]["Layers"]["Position_WORK"]["lic"]])
            )
            # Сохраняем код месторождения
            self.fieldCode = str(feature["oilfield"]).split("_")[0]
           
                
            north = feature.geometry().asPoint().y()
            east = feature.geometry().asPoint().x()
            
            crs_l = self.layerWellHead.crs()
            crs_t = self.crsOutputWellHead
            
            # Создаем преобразование координат
            transform = QgsCoordinateTransform(crs_l, crs_t, QgsProject.instance())
            
            # Исходная точка
            sourcePoint = QgsPointXY(east, north)
    
            # Пересчет
            targetPoint = transform.transform(sourcePoint)
            
            if self.crsOutputWellHead.isGeographic():
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.10f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.10f}")
            else:
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.3f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.3f}")
        
        # # По умолчанию отметка равна 0
        # elevation = 0
        # # Если точка имеет координату Z
        # # if point.is3D():
        # #     elevation = point.z()
        # self.txtWellHeadElevation.setText(f"{elevation:.3f}")
        
        # Выключаем инструмент выбора
        iface.mapCanvas().unsetMapTool(
            self.wellHeadIdentifyTool
        )


    # ======================================================
    # Смена системы координат устья
    # ======================================================

    def wellHeadCrsChanged(self, crs):
        
        self.crsLayerWellHead = self.crsOutputWellHead
        self.crsOutputWellHead = crs
        
        if self.txtWellHeadNorth.text() != '' and self.txtWellHeadEast.text() != '':
            north = float(self.txtWellHeadNorth.text())
            east = float(self.txtWellHeadEast.text())
            
            # Создаем преобразование координат
            transform = QgsCoordinateTransform(
                self.crsLayerWellHead,
                self.crsOutputWellHead,
                QgsProject.instance()
            )
            
            # Исходная точка
            sourcePoint = QgsPointXY(east, north)
    
            # Пересчет
            targetPoint = transform.transform(sourcePoint)
            
            if self.crsOutputWellHead.isGeographic():
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.10f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.10f}")
            else:
                self.txtWellHeadNorth.setText(f"{targetPoint.y():.3f}")
                self.txtWellHeadEast.setText(f"{targetPoint.x():.3f}")


    # ======================================================
    # Дополнительный обработчик выбора слоя устья (просто заглушка (костыль))
    # ======================================================

    # def mMapLayerComboBoxWellHeadChanged(self, layer):
    #     return

    # ======================================================
    # Вкладка "Цели"
    # ======================================================


    def selectTarget(self):
        """Выбор цели"""
    
        layer = QgsProject.instance().mapLayersByName("Targets_WORK")
    
        if not layer:
            QMessageBox.warning(
                self,
                "Внимание",
                "Не найден слой Targets_WORK."
            )
            return 
        
        self.layerTarget = layer[0]
    
        self.targetIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
    
        self.targetIdentifyTool.setLayer(self.layerTarget)
    
        self.targetIdentifyTool.featureIdentified.connect(
            self.targetSelected
        )
    
        iface.mapCanvas().setMapTool(
            self.targetIdentifyTool
        )


    def targetSelected(self, feature):
    
        # Сохраняем выбранную цель
        self.selectedTargets.append(feature)
    

    
        # Определяем СК слоя
        crs = self.layerTarget.crs()
    
        self.crsLayerTarget = crs
        self.crsOutputTarget = crs
        self.addTargetToTable(feature)
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(True)
        self.mQgsProjectionSelectionWidgetTarget.setCrs(crs)
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(False)
    

    
        iface.mapCanvas().unsetMapTool(
            self.targetIdentifyTool
        )


    def addTargetToTable(self, feature):
    
        row = self.tableTargets.rowCount()
        self.tableTargets.insertRow(row)
    
        # ID цели
        self.tableTargets.setItem(
            row,
            0,
            QtWidgets.QTableWidgetItem(str(feature["tid"]))
        )
    
        # Координаты
        north = feature.geometry().asPoint().y()
        east = feature.geometry().asPoint().x()
    
        transform = QgsCoordinateTransform(
            self.layerTarget.crs(),
            self.crsOutputTarget,
            QgsProject.instance()
        )
    
        targetPoint = transform.transform(
            QgsPointXY(east, north)
        )
    
        if self.crsOutputTarget.isGeographic():
            northText = f"{targetPoint.y():.10f}"
            eastText = f"{targetPoint.x():.10f}"
        else:
            northText = f"{targetPoint.y():.3f}"
            eastText = f"{targetPoint.x():.3f}"
    
        self.tableTargets.setItem(
            row,
            1,
            QtWidgets.QTableWidgetItem(northText)
        )
    
        self.tableTargets.setItem(
            row,
            2,
            QtWidgets.QTableWidgetItem(eastText)
        )

        self.tableTargets.setItem(
            row,
            3,
            QtWidgets.QTableWidgetItem(str(feature["ttvd"]))
        )

        return northText, eastText


    # Автоматическое заполнение списка целей в зависимости от слоя

    def targetLayerChanged(self, layer):

        layers = QgsProject.instance().mapLayersByName("Targets_WORK")
        layer = layers[0] if layers else None

        self.cmbTarget.clear()
    
        if layer is None:
            return
    
        if self.fieldCode == "":
            return
    
        for feature in layer.getFeatures():
    
            if str(feature["oilfield"]) == self.fieldCode:
    
                self.cmbTarget.addItem(
                    str(feature["tid"]),
                    feature.id()
                )


    def targetChanged(self, index):
     
        if index < 0:
            return
    
        layers = QgsProject.instance().mapLayersByName("Targets_WORK")
        layer = layers[0] if layers else None
    
        if layer is None:
            return
    
        feature_id = self.cmbTarget.currentData()
    
        if feature_id is None:
            return
    
        # Получаем объект по его id
        feature = layer.getFeature(feature_id)
    
        # Сохраняем выбранную цель
        self.selectedTarget = feature
    
    # ======================================================
    # Смена системы координат целей
    # ======================================================

    def targetCrsChanged(self, crs):

        self.crsOutputTarget = crs
    
        # очистить таблицу
        self.tableTargets.setRowCount(0)
    
        # заполнить заново
        for feature in self.selectedTargets:
            self.addTargetToTable(feature)
    
        # если выбрана текущая цель — обновить поля справа
        if self.selectedTargets:
            feature = self.selectedTargets[-1]
    
            northText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 1
            ).text()
    
            eastText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 2
            ).text()
    
   
