# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MainInclinometrDialog
                                 A QGIS plugin
 Расчет нклинометрии
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2026 by GPN-GEO
        email                : jjj@kkk.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os 
import json
import random

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import Qt

from qgis.core import (
    QgsMapLayerProxyModel,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY,
    QgsVectorLayer,
    QgsField,
    QgsFields,
    QgsFeature
)

# Для функции выбора устья
from qgis.gui import QgsMapToolIdentifyFeature
from qgis.utils import iface

from PyQt5.QtCore import QVariant

from .mathematics import Mathematics
from .layer_manager import LayerManager

from .modules.geodezy import Geodezy
from .modules.inclinometry import Inclinometry

from .ui.tabWellhead import TabWellhead
from .ui.tabInclinometry import TabInclinometry
from .ui.tabSettings import TabSettings
from .ui.tabTarget import TabTarget


# ==========================================================
# Загрузка интерфейса Qt Designer
# ==========================================================

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        "inclinometr_dialog_base.ui"
    ),
    from_imports=True,
    import_from="inclinometr"
)

# ==========================================================
# Главный класс плагина
# ==========================================================

class MainInclinometrDialog(QtWidgets.QDialog, FORM_CLASS):

    # ======================================================
    # Инициализация
    # ======================================================

    def __init__(self, parent=None):
        """Constructor."""

        super(MainInclinometrDialog, self).__init__(parent)
        self.math = Mathematics(self)
        self.setupUi(self)
        self.setFixedSize(self.size())        
        
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        self.show()

        self.layerManager = LayerManager(self)

        self.tabWidget.setCurrentIndex(0)

        tabWellheads_index = self.tabWidget.indexOf(self.tabWellheads)
        self.tabWidget.setTabEnabled(tabWellheads_index, False)

        targets_index = self.tabWidget.indexOf(self.tabTargets)
        self.tabWidget.setTabEnabled(targets_index, False)

        incls_index = self.tabWidget.indexOf(self.tabIncls)
        self.tabWidget.setTabEnabled(incls_index, False)
        
        # =====================================================
        # Вкладка: Позиция / Устье
        # =====================================================

        self.tabWellhead = TabWellhead(self)    
        # Подключаем сигнал на кнопку выбора позиции / устья
        self.btnSelectWellHead.clicked.connect( self.tabWellhead.selectWellHead )
        # Подключаем сигнал на кнопку смены системы координат
        self.mQgsProjectionSelectionWidgetWellHead.crsChanged.connect( self.tabWellhead.wellHeadCrsChanged )
        # Текущая система координат для расчетов
        self.crsOutputWellHead = self.tabWellhead.getCurrentCrs()
        self.tabWellheadInclGoBtn.clicked.connect(self.tabWellhead.inclTabActivate)

        # =====================================================
        # Вкладка: Цели
        # =====================================================

        self.tabTarget = TabTarget(self)
        self.btnSelectTarget.clicked.connect(self.tabTarget.selectTarget)
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(self.tabTarget.targetCrsChanged)

        # =====================================================
        # Вкладка: Инклинометрия
        # =====================================================

        self.tabInclinometry = TabInclinometry(self)
        self.tabInclTargetGoBtn.clicked.connect(self.tabInclinometry.targetTabActivate)


        # =====================================================
        # Вкладка: Настройка
        # =====================================================

        self.tabSettings = TabSettings(self)
        # Источник слоёв — текущий проект QGIS
        self.tabSettingsWellheadMLCBox.setProject(QgsProject.instance())
        self.tabSettingsTargetsMLCBox.setProject(QgsProject.instance())
        self.tabSettingsBoresMLCBox.setProject(QgsProject.instance())

        # Применяем фильтры после установки проекта
        self.tabSettings.filterWellheadLayers()
        self.tabSettings.filterWelltargetLayers()
        self.tabSettings.filterWellboreLayers()

        # Если слои уже есть в проекте — выбираем их
        self.tabSettings.selectWellheadInComboBox()
        self.tabSettings.selectWelltargetInComboBox()
        self.tabSettings.selectWellboreInComboBox()

        # Повторная фильтрация при добавлении/удалении слоёв
        QgsProject.instance().layersAdded.connect(self.tabSettings._onLayersChanged)
        QgsProject.instance().layersRemoved.connect(self.tabSettings._onLayersChanged)

        # Подключаем кнопки
        self.tabSettingsWellheadBtn.clicked.connect(self.tabSettings.wellheadLayerAdd)
        self.tabSettingsTargetsBtn.clicked.connect(self.tabSettings.welltargetLayerAdd)
        self.tabSettingsBoresBtn.clicked.connect(self.tabSettings.wellboreLayerAdd)
        self.tabSettingsWellheadGoBtn.clicked.connect(self.tabSettings.wellheadTabActivate)