# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MainInclinometrDialog
                                 A QGIS plugin
 Расчет нклинометрии
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2026 by GPN-GEO
        email                : jjj@kkk.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os 
import json
import random

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import Qt

from qgis.core import (
    QgsMapLayerProxyModel,
    QgsCoordinateTransform,
    QgsProject,
    QgsPointXY,
    QgsVectorLayer,
    QgsField,
    QgsFields,
    QgsFeature
)

# Для функции выбора устья
from qgis.gui import QgsMapToolIdentifyFeature
from qgis.utils import iface

from PyQt5.QtCore import QVariant

from .mathematics import Mathematics
from .layer_manager import LayerManager

from .modules.geodezy import Geodezy
from .modules.inclinometry import Inclinometry

from .ui.tabWellhead import TabWellhead
from .ui.tabInclinometry import TabInclinometry
from .ui.tabSettings import TabSettings

# ==========================================================
# Загрузка интерфейса Qt Designer
# ==========================================================

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        "inclinometr_dialog_base.ui"
    ),
    from_imports=True,
    import_from="inclinometr"
)

# ==========================================================
# Главный класс плагина
# ==========================================================

class MainInclinometrDialog(QtWidgets.QDialog, FORM_CLASS):

    # ======================================================
    # Инициализация
    # ======================================================

    def __init__(self, parent=None):
        """Constructor."""

        super(MainInclinometrDialog, self).__init__(parent)
        self.math = Mathematics(self)
        self.setupUi(self)
        self.setFixedSize(self.size())        
        
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        self.show()

        self.layerManager = LayerManager(self)

        # =====================================================
        # Загрузка плагина
        # =====================================================

        # Вкладки:
        # 0 - "Позиция": Активная вкладка при запуске плагина
        # 1 - "Инклинометрия": Не активная вкладка до выбора позиции (устья)
        # 2 - "Цели": Не активная вкладка до расчета инклинометрии
        # self.tabWidget.setTabEnabled(1, False)
        # self.tabWidget.setTabEnabled(2, False)
        # self.tabWidget.setTabEnabled(3, False)
        self.tabWidget.setCurrentIndex(0)

        ust_index = self.tabWidget.indexOf(self.Ust)
        self.tabWidget.setTabEnabled(ust_index, False)
        
        # Инструмент выбора
        self.wellHeadIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.targetIdentifyTool = None
        # Здесь будет храниться выбранное устье
        self.selectedWellHead = None
        # Система координат слоя
        self.crsLayerWellHead = None

        # Выбранная система координат
        self.crsOutputWellHead = None

        # =====================================================
        # Вкладка: Позиция / Устье
        # =====================================================

        self.tabWellhead = TabWellhead(self)    
        # Подключаем сигнал на кнопку выбора позиции / устья
        self.btnSelectWellHead.clicked.connect( self.tabWellhead.selectWellHead )
        # Подключаем сигнал на кнопку смены системы координат
        self.mQgsProjectionSelectionWidgetWellHead.crsChanged.connect( self.tabWellhead.wellHeadCrsChanged )
        # Текущая система координат для расчетов
        self.crsOutputWellHead = self.tabWellhead.getCurrentCrs()

        # =====================================================
        # Вкладка: Инклинометрия
        # =====================================================

        self.tabInclinometry = TabInclinometry(self)

        # =====================================================
        # Вкладка: Настройка
        # =====================================================

        self.tabSettings = TabSettings(self)
        # Источник слоёв — текущий проект QGIS
        self.tabSettingsWellheadMLCBox.setProject(QgsProject.instance())
        self.tabSettingsTargetsMLCBox.setProject(QgsProject.instance())
        self.tabSettingsBoresMLCBox.setProject(QgsProject.instance())

        # Применяем фильтры после установки проекта
        self.tabSettings.filterWellheadLayers()
        self.tabSettings.filterWelltargetLayers()
        self.tabSettings.filterWellboreLayers()

        # Если слои уже есть в проекте — выбираем их
        self.tabSettings.selectWellheadInComboBox()
        self.tabSettings.selectWelltargetInComboBox()
        self.tabSettings.selectWellboreInComboBox()

        # Повторная фильтрация при добавлении/удалении слоёв
        QgsProject.instance().layersAdded.connect(self.tabSettings._onLayersChanged)
        QgsProject.instance().layersRemoved.connect(self.tabSettings._onLayersChanged)

        # Подключаем кнопки
        self.tabSettingsWellheadBtn.clicked.connect(self.tabSettings.wellheadLayerAdd)
        self.tabSettingsTargetsBtn.clicked.connect(self.tabSettings.welltargetLayerAdd)
        self.tabSettingsBoresBtn.clicked.connect(self.tabSettings.wellboreLayerAdd)
        self.tabSettingsWellheadGoBtn.clicked.connect(self.tabSettings.wellheadTabActivate)

 

        # -----------------------------------------------------------------------------------------
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )

        # %% Вкладка --- Цели ---

        
        self.selectedTarget = None

        # %% Вкладка --- Слои

        # исходные слои которые БУДУТ включены в рабочие слои
        self.positionLayers = []
        self.targetLayers = []
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxPositions.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        # Фильтр только точечных слоев
        self.mMapLayerComboBoxTargets.setFilters(
            QgsMapLayerProxyModel.PointLayer
        )
        
        
        # Подключение кнопок для выбора слоев
 
        self.btnAddPositionLayer.clicked.connect(self.layerManager.addPositionLayer)
        self.btnRemovePositionLayer.clicked.connect(self.layerManager.removePositionLayer)

        self.btnAddTargetLayer.clicked.connect(self.layerManager.addTargetLayer)
        self.btnRemoveTargetLayer.clicked.connect(self.layerManager.removeTargetLayer)

        # добавление кнопок создания рабочих слоев
        self.btnCreatePositionsLayer.clicked.connect(self.layerManager.createPositionsLayer)
        self.btnCreateTargetsLayer.clicked.connect(self.layerManager.createTargetsLayer)
        
        # Рабочие слои
        self.layerPositions = None
        self.layerTargets = None
        self.layerOilfields = None
        
        self.btnCreateOilFieldsLayer.clicked.connect(self.layerManager.createOilFieldsLayer)
        
        self.btnSelectTarget.clicked.connect(
            self.selectTarget
        )
        
        # Система координат слоя целей
        self.crsLayerTarget = None
        
        # Система координат вывода целей
        self.crsOutputTarget = None
        
        
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(
            self.targetCrsChanged
        )
        
        
        self.selectedTargets = []

        # ПРИЧИНА ДВОЙНОГО ВЫЗОВА ПРОВОДНИКА
        # self.btnLoadInclinometry.clicked.connect(
        #     self.math.loadInclinometry
        # )


        # self.btnCalculateInclinometry.clicked.connect(
        #     self.math.calculateInclinometry
        # )
        # self.btnCalculateDeviation.clicked.connect(
        #     self.math.calculationDeviation
        # )
        # self.geodezy = Geodezy()
        # self.inclinometry = Inclinometry()


    def selectFeature(self, callback):
        """Универсальная функция выбора объекта на карте"""
        layers = QgsProject.instance().mapLayersByName("Positions_WORK")
        layer = layers[0] if layers else None
        self.crsLayerWellHead = layer.crs()
        self.crsOutputWellHead = layer.crs()
        self.layerWellHead = layer

        if layer is None:
            QMessageBox.warning(
                self,
                "Внимание",
                "Сначала выберите слой."
            )
            return

        self.wellHeadIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
        self.wellHeadIdentifyTool.setLayer(layer)
        self.wellHeadIdentifyTool.featureIdentified.connect(
            callback
        )

        iface.mapCanvas().setMapTool(
            self.wellHeadIdentifyTool
        )

    # ======================================================
    # Вкладка "Цели"
    # ======================================================


    def selectTarget(self):
        """Выбор цели"""
    
        layer = QgsProject.instance().mapLayersByName("Targets_WORK")
    
        if not layer:
            QMessageBox.warning(
                self,
                "Внимание",
                "Не найден слой Targets_WORK."
            )
            return 
        
        self.layerTarget = layer[0]
    
        self.targetIdentifyTool = QgsMapToolIdentifyFeature(
            iface.mapCanvas()
        )
    
        self.targetIdentifyTool.setLayer(self.layerTarget)
    
        self.targetIdentifyTool.featureIdentified.connect(
            self.targetSelected
        )
    
        iface.mapCanvas().setMapTool(
            self.targetIdentifyTool
        )


    def targetSelected(self, feature):
    
        # Сохраняем выбранную цель
        self.selectedTargets.append(feature)
    
        # Определяем СК слоя
        crs = self.layerTarget.crs()
    
        self.crsLayerTarget = crs
        self.crsOutputTarget = crs
        self.addTargetToTable(feature)
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(True)
        self.mQgsProjectionSelectionWidgetTarget.setCrs(crs)
        self.mQgsProjectionSelectionWidgetTarget.blockSignals(False)
    
        iface.mapCanvas().unsetMapTool(
            self.targetIdentifyTool
        )


    def addTargetToTable(self, feature):
    
        row = self.tableTargets.rowCount()
        self.tableTargets.insertRow(row)
    
        # ID цели
        self.tableTargets.setItem(
            row,
            0,
            QtWidgets.QTableWidgetItem(str(feature["tid"]))
        )
    
        # Координаты
        north = feature.geometry().asPoint().y()
        east = feature.geometry().asPoint().x()
    
        transform = QgsCoordinateTransform(
            self.layerTarget.crs(),
            self.crsOutputTarget,
            QgsProject.instance()
        )
    
        targetPoint = transform.transform(
            QgsPointXY(east, north)
        )
    
        if self.crsOutputTarget.isGeographic():
            northText = f"{targetPoint.y():.10f}"
            eastText = f"{targetPoint.x():.10f}"
        else:
            northText = f"{targetPoint.y():.3f}"
            eastText = f"{targetPoint.x():.3f}"
    
        self.tableTargets.setItem(
            row,
            1,
            QtWidgets.QTableWidgetItem(northText)
        )
    
        self.tableTargets.setItem(
            row,
            2,
            QtWidgets.QTableWidgetItem(eastText)
        )

        self.tableTargets.setItem(
            row,
            3,
            QtWidgets.QTableWidgetItem(str(feature["ttvd"]))
        )

        return northText, eastText

    # ======================================================
    # Смена системы координат целей
    # ======================================================

    def targetCrsChanged(self, crs):

        self.crsOutputTarget = crs
    
        # очистить таблицу
        self.tableTargets.setRowCount(0)
    
        # заполнить заново
        for feature in self.selectedTargets:
            self.addTargetToTable(feature)
    
        # если выбрана текущая цель — обновить поля справа
        if self.selectedTargets:
            feature = self.selectedTargets[-1]
    
            northText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 1
            ).text()
    
            eastText = self.tableTargets.item(
                self.tableTargets.rowCount()-1, 2
            ).text()

